### ISSUE TITLE
Is this a good way to start with SSR and SolidJS ?

### ISSUE THREAD

**Issue by jbanety** [lxsmnsyc/rigidity#1]
Hi @lxsmnsyc,
What a great work you've done !
Is this production ready ? Or maybe without warranty ?

I'm looking to build an ecommerce app with SolidJS and I want to do SSR.
Is Caldaria a good way to start with SSR and SolidJS ?

Your packages aren't published to npm repo. Do you plan to publish them ?

**Comment by lxsmnsyc** [comment]
Hello, thanks for taking interest. A bit of fair warning though that since I haven't published anything yet, this isn't for production use yet. The reason I haven't published yet is because

1. the SSR is still buggy (I am coordinating with Ryan Carniato for fixes)
2. the live reload feature is still slow.
3. The API is still rough and may change.

For starters, I do recommend [SolidStart](https://github.com/solidjs/solid-statt) but it is still in alpha, there's also [Astro](https://astro.build) however using it means there's no SPA navigation.

**Comment by jbanety** [comment]
What are your goals?
Your project looks interesting and I might participate debug and enhance it.

**Comment by lxsmnsyc** [comment]
the MVP is definitely there but the DX isn't. I really wanted to improve the DX specially on the live reload. If the SSR is fixed + the live reload is smooth then I can safely say Caldaria is 100% ready to use

**Comment by jbanety** [comment]
👍 
How can I help ?

**Comment by lxsmnsyc** [comment]
Not yet at the moment. I'm still have some researching to do

**Comment by mb21** [comment]
I have a related question to "What are your goals?":
What does this differently/better than [SolidStart](https://start.solidjs.com/)?

**Comment by lxsmnsyc** [comment]
@mb21 this project is already dead. I haven't really had the time to archive this repo.

Also, I'm actively working on SolidStart.
